on:
  push:
    branches:
      - main
name: CI
jobs:
  acceptance_tests_dashboard_namespace:
    name: Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Install deps
        run: npm install
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          # or 'stable'
          chrome-version: 127
      - name: Testcade
        run: npx testcafe 'chrome:${{ steps.setup-chrome.outputs.chrome-path }} --headless --window-size=1920x1080' index.js
